CREATE TABLE users(
id SERIAL PRIMARY KEY,
email VARCHAR(100) NOT NULL UNIQUE,
password VARCHAR(100)
)

CREATE TABLE users(
    id SERIAL PRIMARY KEY,
    email VARCHAR(100) not NULL UNIQUE,
    password VARCHAR(100)

    
)

